/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DtoRegisterUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoRegisterUserRequest{}

// DtoRegisterUserRequest struct for DtoRegisterUserRequest
type DtoRegisterUserRequest struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

type _DtoRegisterUserRequest DtoRegisterUserRequest

// NewDtoRegisterUserRequest instantiates a new DtoRegisterUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoRegisterUserRequest(email string, password string) *DtoRegisterUserRequest {
	this := DtoRegisterUserRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewDtoRegisterUserRequestWithDefaults instantiates a new DtoRegisterUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoRegisterUserRequestWithDefaults() *DtoRegisterUserRequest {
	this := DtoRegisterUserRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *DtoRegisterUserRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *DtoRegisterUserRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *DtoRegisterUserRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *DtoRegisterUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *DtoRegisterUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *DtoRegisterUserRequest) SetPassword(v string) {
	o.Password = v
}

func (o DtoRegisterUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoRegisterUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *DtoRegisterUserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoRegisterUserRequest := _DtoRegisterUserRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoRegisterUserRequest)

	if err != nil {
		return err
	}

	*o = DtoRegisterUserRequest(varDtoRegisterUserRequest)

	return err
}

type NullableDtoRegisterUserRequest struct {
	value *DtoRegisterUserRequest
	isSet bool
}

func (v NullableDtoRegisterUserRequest) Get() *DtoRegisterUserRequest {
	return v.value
}

func (v *NullableDtoRegisterUserRequest) Set(val *DtoRegisterUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoRegisterUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoRegisterUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoRegisterUserRequest(val *DtoRegisterUserRequest) *NullableDtoRegisterUserRequest {
	return &NullableDtoRegisterUserRequest{value: val, isSet: true}
}

func (v NullableDtoRegisterUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoRegisterUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


