/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CollectionsPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollectionsPost201Response{}

// CollectionsPost201Response struct for CollectionsPost201Response
type CollectionsPost201Response struct {
	Data *ModelsCollection `json:"data,omitempty"`
	Error *string `json:"error,omitempty"`
	IsSuccess *bool `json:"is_success,omitempty"`
}

// NewCollectionsPost201Response instantiates a new CollectionsPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionsPost201Response() *CollectionsPost201Response {
	this := CollectionsPost201Response{}
	return &this
}

// NewCollectionsPost201ResponseWithDefaults instantiates a new CollectionsPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionsPost201ResponseWithDefaults() *CollectionsPost201Response {
	this := CollectionsPost201Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CollectionsPost201Response) GetData() ModelsCollection {
	if o == nil || IsNil(o.Data) {
		var ret ModelsCollection
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionsPost201Response) GetDataOk() (*ModelsCollection, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CollectionsPost201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ModelsCollection and assigns it to the Data field.
func (o *CollectionsPost201Response) SetData(v ModelsCollection) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CollectionsPost201Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionsPost201Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CollectionsPost201Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CollectionsPost201Response) SetError(v string) {
	o.Error = &v
}

// GetIsSuccess returns the IsSuccess field value if set, zero value otherwise.
func (o *CollectionsPost201Response) GetIsSuccess() bool {
	if o == nil || IsNil(o.IsSuccess) {
		var ret bool
		return ret
	}
	return *o.IsSuccess
}

// GetIsSuccessOk returns a tuple with the IsSuccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionsPost201Response) GetIsSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSuccess) {
		return nil, false
	}
	return o.IsSuccess, true
}

// HasIsSuccess returns a boolean if a field has been set.
func (o *CollectionsPost201Response) HasIsSuccess() bool {
	if o != nil && !IsNil(o.IsSuccess) {
		return true
	}

	return false
}

// SetIsSuccess gets a reference to the given bool and assigns it to the IsSuccess field.
func (o *CollectionsPost201Response) SetIsSuccess(v bool) {
	o.IsSuccess = &v
}

func (o CollectionsPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollectionsPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.IsSuccess) {
		toSerialize["is_success"] = o.IsSuccess
	}
	return toSerialize, nil
}

type NullableCollectionsPost201Response struct {
	value *CollectionsPost201Response
	isSet bool
}

func (v NullableCollectionsPost201Response) Get() *CollectionsPost201Response {
	return v.value
}

func (v *NullableCollectionsPost201Response) Set(val *CollectionsPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionsPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionsPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionsPost201Response(val *CollectionsPost201Response) *NullableCollectionsPost201Response {
	return &NullableCollectionsPost201Response{value: val, isSet: true}
}

func (v NullableCollectionsPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionsPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


