/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelsMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsMetric{}

// ModelsMetric struct for ModelsMetric
type ModelsMetric struct {
	AvgFileSizeMb *float32 `json:"avg_file_size_mb,omitempty"`
	AvgTimeProcessed *float32 `json:"avg_time_processed,omitempty"`
	FilesProcessed *int32 `json:"files_processed,omitempty"`
	Id *int32 `json:"id,omitempty"`
	LatestFileProcessedTimestamp *string `json:"latest_file_processed_timestamp,omitempty"`
	MaxTimeProcessed *float32 `json:"max_time_processed,omitempty"`
	MinTimeProcessed *float32 `json:"min_time_processed,omitempty"`
	Top10MostFreqWords []ModelsWord `json:"top_10_most_freq_words,omitempty"`
	TotalFileSizeMb *float32 `json:"total_file_size_mb,omitempty"`
}

// NewModelsMetric instantiates a new ModelsMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsMetric() *ModelsMetric {
	this := ModelsMetric{}
	return &this
}

// NewModelsMetricWithDefaults instantiates a new ModelsMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsMetricWithDefaults() *ModelsMetric {
	this := ModelsMetric{}
	return &this
}

// GetAvgFileSizeMb returns the AvgFileSizeMb field value if set, zero value otherwise.
func (o *ModelsMetric) GetAvgFileSizeMb() float32 {
	if o == nil || IsNil(o.AvgFileSizeMb) {
		var ret float32
		return ret
	}
	return *o.AvgFileSizeMb
}

// GetAvgFileSizeMbOk returns a tuple with the AvgFileSizeMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetAvgFileSizeMbOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgFileSizeMb) {
		return nil, false
	}
	return o.AvgFileSizeMb, true
}

// HasAvgFileSizeMb returns a boolean if a field has been set.
func (o *ModelsMetric) HasAvgFileSizeMb() bool {
	if o != nil && !IsNil(o.AvgFileSizeMb) {
		return true
	}

	return false
}

// SetAvgFileSizeMb gets a reference to the given float32 and assigns it to the AvgFileSizeMb field.
func (o *ModelsMetric) SetAvgFileSizeMb(v float32) {
	o.AvgFileSizeMb = &v
}

// GetAvgTimeProcessed returns the AvgTimeProcessed field value if set, zero value otherwise.
func (o *ModelsMetric) GetAvgTimeProcessed() float32 {
	if o == nil || IsNil(o.AvgTimeProcessed) {
		var ret float32
		return ret
	}
	return *o.AvgTimeProcessed
}

// GetAvgTimeProcessedOk returns a tuple with the AvgTimeProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetAvgTimeProcessedOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgTimeProcessed) {
		return nil, false
	}
	return o.AvgTimeProcessed, true
}

// HasAvgTimeProcessed returns a boolean if a field has been set.
func (o *ModelsMetric) HasAvgTimeProcessed() bool {
	if o != nil && !IsNil(o.AvgTimeProcessed) {
		return true
	}

	return false
}

// SetAvgTimeProcessed gets a reference to the given float32 and assigns it to the AvgTimeProcessed field.
func (o *ModelsMetric) SetAvgTimeProcessed(v float32) {
	o.AvgTimeProcessed = &v
}

// GetFilesProcessed returns the FilesProcessed field value if set, zero value otherwise.
func (o *ModelsMetric) GetFilesProcessed() int32 {
	if o == nil || IsNil(o.FilesProcessed) {
		var ret int32
		return ret
	}
	return *o.FilesProcessed
}

// GetFilesProcessedOk returns a tuple with the FilesProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetFilesProcessedOk() (*int32, bool) {
	if o == nil || IsNil(o.FilesProcessed) {
		return nil, false
	}
	return o.FilesProcessed, true
}

// HasFilesProcessed returns a boolean if a field has been set.
func (o *ModelsMetric) HasFilesProcessed() bool {
	if o != nil && !IsNil(o.FilesProcessed) {
		return true
	}

	return false
}

// SetFilesProcessed gets a reference to the given int32 and assigns it to the FilesProcessed field.
func (o *ModelsMetric) SetFilesProcessed(v int32) {
	o.FilesProcessed = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsMetric) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsMetric) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelsMetric) SetId(v int32) {
	o.Id = &v
}

// GetLatestFileProcessedTimestamp returns the LatestFileProcessedTimestamp field value if set, zero value otherwise.
func (o *ModelsMetric) GetLatestFileProcessedTimestamp() string {
	if o == nil || IsNil(o.LatestFileProcessedTimestamp) {
		var ret string
		return ret
	}
	return *o.LatestFileProcessedTimestamp
}

// GetLatestFileProcessedTimestampOk returns a tuple with the LatestFileProcessedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetLatestFileProcessedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.LatestFileProcessedTimestamp) {
		return nil, false
	}
	return o.LatestFileProcessedTimestamp, true
}

// HasLatestFileProcessedTimestamp returns a boolean if a field has been set.
func (o *ModelsMetric) HasLatestFileProcessedTimestamp() bool {
	if o != nil && !IsNil(o.LatestFileProcessedTimestamp) {
		return true
	}

	return false
}

// SetLatestFileProcessedTimestamp gets a reference to the given string and assigns it to the LatestFileProcessedTimestamp field.
func (o *ModelsMetric) SetLatestFileProcessedTimestamp(v string) {
	o.LatestFileProcessedTimestamp = &v
}

// GetMaxTimeProcessed returns the MaxTimeProcessed field value if set, zero value otherwise.
func (o *ModelsMetric) GetMaxTimeProcessed() float32 {
	if o == nil || IsNil(o.MaxTimeProcessed) {
		var ret float32
		return ret
	}
	return *o.MaxTimeProcessed
}

// GetMaxTimeProcessedOk returns a tuple with the MaxTimeProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetMaxTimeProcessedOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxTimeProcessed) {
		return nil, false
	}
	return o.MaxTimeProcessed, true
}

// HasMaxTimeProcessed returns a boolean if a field has been set.
func (o *ModelsMetric) HasMaxTimeProcessed() bool {
	if o != nil && !IsNil(o.MaxTimeProcessed) {
		return true
	}

	return false
}

// SetMaxTimeProcessed gets a reference to the given float32 and assigns it to the MaxTimeProcessed field.
func (o *ModelsMetric) SetMaxTimeProcessed(v float32) {
	o.MaxTimeProcessed = &v
}

// GetMinTimeProcessed returns the MinTimeProcessed field value if set, zero value otherwise.
func (o *ModelsMetric) GetMinTimeProcessed() float32 {
	if o == nil || IsNil(o.MinTimeProcessed) {
		var ret float32
		return ret
	}
	return *o.MinTimeProcessed
}

// GetMinTimeProcessedOk returns a tuple with the MinTimeProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetMinTimeProcessedOk() (*float32, bool) {
	if o == nil || IsNil(o.MinTimeProcessed) {
		return nil, false
	}
	return o.MinTimeProcessed, true
}

// HasMinTimeProcessed returns a boolean if a field has been set.
func (o *ModelsMetric) HasMinTimeProcessed() bool {
	if o != nil && !IsNil(o.MinTimeProcessed) {
		return true
	}

	return false
}

// SetMinTimeProcessed gets a reference to the given float32 and assigns it to the MinTimeProcessed field.
func (o *ModelsMetric) SetMinTimeProcessed(v float32) {
	o.MinTimeProcessed = &v
}

// GetTop10MostFreqWords returns the Top10MostFreqWords field value if set, zero value otherwise.
func (o *ModelsMetric) GetTop10MostFreqWords() []ModelsWord {
	if o == nil || IsNil(o.Top10MostFreqWords) {
		var ret []ModelsWord
		return ret
	}
	return o.Top10MostFreqWords
}

// GetTop10MostFreqWordsOk returns a tuple with the Top10MostFreqWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetTop10MostFreqWordsOk() ([]ModelsWord, bool) {
	if o == nil || IsNil(o.Top10MostFreqWords) {
		return nil, false
	}
	return o.Top10MostFreqWords, true
}

// HasTop10MostFreqWords returns a boolean if a field has been set.
func (o *ModelsMetric) HasTop10MostFreqWords() bool {
	if o != nil && !IsNil(o.Top10MostFreqWords) {
		return true
	}

	return false
}

// SetTop10MostFreqWords gets a reference to the given []ModelsWord and assigns it to the Top10MostFreqWords field.
func (o *ModelsMetric) SetTop10MostFreqWords(v []ModelsWord) {
	o.Top10MostFreqWords = v
}

// GetTotalFileSizeMb returns the TotalFileSizeMb field value if set, zero value otherwise.
func (o *ModelsMetric) GetTotalFileSizeMb() float32 {
	if o == nil || IsNil(o.TotalFileSizeMb) {
		var ret float32
		return ret
	}
	return *o.TotalFileSizeMb
}

// GetTotalFileSizeMbOk returns a tuple with the TotalFileSizeMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsMetric) GetTotalFileSizeMbOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalFileSizeMb) {
		return nil, false
	}
	return o.TotalFileSizeMb, true
}

// HasTotalFileSizeMb returns a boolean if a field has been set.
func (o *ModelsMetric) HasTotalFileSizeMb() bool {
	if o != nil && !IsNil(o.TotalFileSizeMb) {
		return true
	}

	return false
}

// SetTotalFileSizeMb gets a reference to the given float32 and assigns it to the TotalFileSizeMb field.
func (o *ModelsMetric) SetTotalFileSizeMb(v float32) {
	o.TotalFileSizeMb = &v
}

func (o ModelsMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvgFileSizeMb) {
		toSerialize["avg_file_size_mb"] = o.AvgFileSizeMb
	}
	if !IsNil(o.AvgTimeProcessed) {
		toSerialize["avg_time_processed"] = o.AvgTimeProcessed
	}
	if !IsNil(o.FilesProcessed) {
		toSerialize["files_processed"] = o.FilesProcessed
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LatestFileProcessedTimestamp) {
		toSerialize["latest_file_processed_timestamp"] = o.LatestFileProcessedTimestamp
	}
	if !IsNil(o.MaxTimeProcessed) {
		toSerialize["max_time_processed"] = o.MaxTimeProcessed
	}
	if !IsNil(o.MinTimeProcessed) {
		toSerialize["min_time_processed"] = o.MinTimeProcessed
	}
	if !IsNil(o.Top10MostFreqWords) {
		toSerialize["top_10_most_freq_words"] = o.Top10MostFreqWords
	}
	if !IsNil(o.TotalFileSizeMb) {
		toSerialize["total_file_size_mb"] = o.TotalFileSizeMb
	}
	return toSerialize, nil
}

type NullableModelsMetric struct {
	value *ModelsMetric
	isSet bool
}

func (v NullableModelsMetric) Get() *ModelsMetric {
	return v.value
}

func (v *NullableModelsMetric) Set(val *ModelsMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsMetric(val *ModelsMetric) *NullableModelsMetric {
	return &NullableModelsMetric{value: val, isSet: true}
}

func (v NullableModelsMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


