/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VersionGet200ResponseAllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionGet200ResponseAllOfData{}

// VersionGet200ResponseAllOfData struct for VersionGet200ResponseAllOfData
type VersionGet200ResponseAllOfData struct {
	Version *string `json:"version,omitempty"`
}

// NewVersionGet200ResponseAllOfData instantiates a new VersionGet200ResponseAllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionGet200ResponseAllOfData() *VersionGet200ResponseAllOfData {
	this := VersionGet200ResponseAllOfData{}
	return &this
}

// NewVersionGet200ResponseAllOfDataWithDefaults instantiates a new VersionGet200ResponseAllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionGet200ResponseAllOfDataWithDefaults() *VersionGet200ResponseAllOfData {
	this := VersionGet200ResponseAllOfData{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *VersionGet200ResponseAllOfData) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VersionGet200ResponseAllOfData) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *VersionGet200ResponseAllOfData) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *VersionGet200ResponseAllOfData) SetVersion(v string) {
	o.Version = &v
}

func (o VersionGet200ResponseAllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionGet200ResponseAllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableVersionGet200ResponseAllOfData struct {
	value *VersionGet200ResponseAllOfData
	isSet bool
}

func (v NullableVersionGet200ResponseAllOfData) Get() *VersionGet200ResponseAllOfData {
	return v.value
}

func (v *NullableVersionGet200ResponseAllOfData) Set(val *VersionGet200ResponseAllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionGet200ResponseAllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionGet200ResponseAllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionGet200ResponseAllOfData(val *VersionGet200ResponseAllOfData) *NullableVersionGet200ResponseAllOfData {
	return &NullableVersionGet200ResponseAllOfData{value: val, isSet: true}
}

func (v NullableVersionGet200ResponseAllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionGet200ResponseAllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


