/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DtoUpdateCollectionReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateCollectionReq{}

// DtoUpdateCollectionReq struct for DtoUpdateCollectionReq
type DtoUpdateCollectionReq struct {
	Name string `json:"name"`
}

type _DtoUpdateCollectionReq DtoUpdateCollectionReq

// NewDtoUpdateCollectionReq instantiates a new DtoUpdateCollectionReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateCollectionReq(name string) *DtoUpdateCollectionReq {
	this := DtoUpdateCollectionReq{}
	this.Name = name
	return &this
}

// NewDtoUpdateCollectionReqWithDefaults instantiates a new DtoUpdateCollectionReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateCollectionReqWithDefaults() *DtoUpdateCollectionReq {
	this := DtoUpdateCollectionReq{}
	return &this
}

// GetName returns the Name field value
func (o *DtoUpdateCollectionReq) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DtoUpdateCollectionReq) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DtoUpdateCollectionReq) SetName(v string) {
	o.Name = v
}

func (o DtoUpdateCollectionReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateCollectionReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *DtoUpdateCollectionReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDtoUpdateCollectionReq := _DtoUpdateCollectionReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDtoUpdateCollectionReq)

	if err != nil {
		return err
	}

	*o = DtoUpdateCollectionReq(varDtoUpdateCollectionReq)

	return err
}

type NullableDtoUpdateCollectionReq struct {
	value *DtoUpdateCollectionReq
	isSet bool
}

func (v NullableDtoUpdateCollectionReq) Get() *DtoUpdateCollectionReq {
	return v.value
}

func (v *NullableDtoUpdateCollectionReq) Set(val *DtoUpdateCollectionReq) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateCollectionReq) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateCollectionReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateCollectionReq(val *DtoUpdateCollectionReq) *NullableDtoUpdateCollectionReq {
	return &NullableDtoUpdateCollectionReq{value: val, isSet: true}
}

func (v NullableDtoUpdateCollectionReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateCollectionReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


