/*
TF-IDF counter API

API for document processing using TF-IDF algorithm

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DtoUpdateUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DtoUpdateUserRequest{}

// DtoUpdateUserRequest struct for DtoUpdateUserRequest
type DtoUpdateUserRequest struct {
	Password *string `json:"password,omitempty"`
}

// NewDtoUpdateUserRequest instantiates a new DtoUpdateUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDtoUpdateUserRequest() *DtoUpdateUserRequest {
	this := DtoUpdateUserRequest{}
	return &this
}

// NewDtoUpdateUserRequestWithDefaults instantiates a new DtoUpdateUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDtoUpdateUserRequestWithDefaults() *DtoUpdateUserRequest {
	this := DtoUpdateUserRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *DtoUpdateUserRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DtoUpdateUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *DtoUpdateUserRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *DtoUpdateUserRequest) SetPassword(v string) {
	o.Password = &v
}

func (o DtoUpdateUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DtoUpdateUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableDtoUpdateUserRequest struct {
	value *DtoUpdateUserRequest
	isSet bool
}

func (v NullableDtoUpdateUserRequest) Get() *DtoUpdateUserRequest {
	return v.value
}

func (v *NullableDtoUpdateUserRequest) Set(val *DtoUpdateUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDtoUpdateUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDtoUpdateUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDtoUpdateUserRequest(val *DtoUpdateUserRequest) *NullableDtoUpdateUserRequest {
	return &NullableDtoUpdateUserRequest{value: val, isSet: true}
}

func (v NullableDtoUpdateUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDtoUpdateUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


